{% set name = "dash-pydantic-form" %}
{% set version = "0.8.2" %}
{% set python_min = 3.10 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_pydantic_form-{{ version }}.tar.gz
  sha256: f9948b82a60cef58b8c261a5d7a514d224b71a0c6029e776925f2002e0cb02bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=67
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }},<3.13
    - dash >=2.16
    - dash-mantine-components >=0.14.5
    - dash-iconify
    - dash-ag-grid >=31
    - pandas
    - pydantic ==2.*
    - fsspec

test:
  imports:
    - dash_pydantic_form
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://pydf-docs.onrender.com
  summary: Create Dash forms from pydantic objects
  dev_url: https://github.com/RenaudLN/dash-pydantic-form
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RenaudLN
