{% set name = "dash-pydantic-form" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_pydantic_form-{{ version }}.tar.gz
  sha256: 5f73e125f6aba9dc30178e6706646d905a7b524580d846dcf660c056a2cf952a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools >=67
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.10,<3.13
    - dash >=2.16
    - dash-mantine-components >=0.14.5
    - dash-iconify
    - dash-ag-grid >=31
    - pandas
    - pydantic ==2.*
    - fsspec

test:
  imports:
    - dash_pydantic_form
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pydf-docs.onrender.com
  summary: Create Dash forms from pydantic objects
  dev_url: https://github.com/RenaudLN/dash-pydantic-form
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RenaudLN
